// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package utils

// Linked list implementation from the Go standard library.

// ConnectionIDEntryElement is an element of a linked list.
type ConnectionIDEntryElement struct {
	// Next and previous pointers in the doubly-linked list of elements.
	// To simplify the implementation, internally a list l is implemented
	// as a ring, such that &l.root is both the next element of the last
	// list element (l.Back()) and the previous element of the first list
	// element (l.Front()).
	next, prev *ConnectionIDEntryElement

	// The list to which this element belongs.
	list *ConnectionIDEntryList

	// The value stored with this element.
	Value ConnectionIDEntry
}

// Next returns the next list element or nil.
func (e *ConnectionIDEntryElement) Next() *ConnectionIDEntryElement {
	if p := e.next; e.list != nil && p != &e.list.root {
		return p
	}
	return nil
}

// Prev returns the previous list element or nil.
func (e *ConnectionIDEntryElement) Prev() *ConnectionIDEntryElement {
	if p := e.prev; e.list != nil && p != &e.list.root {
		return p
	}
	return nil
}

// ConnectionIDEntryList is a linked list of ConnectionIDEntrys.
type ConnectionIDEntryList struct {
	root ConnectionIDEntryElement // sentinel list element, only &root, root.prev, and root.next are used
	len  int                      // current list length excluding (this) sentinel element
}

// Init initializes or clears list l.
func (l *ConnectionIDEntryList) Init() *ConnectionIDEntryList {
	l.root.next = &l.root
	l.root.prev = &l.root
	l.len = 0
	return l
}

// NewConnectionIDEntryList returns an initialized list.
func NewConnectionIDEntryList() *ConnectionIDEntryList { return new(ConnectionIDEntryList).Init() }

// Len returns the number of elements of list l.
// The complexity is O(1).
func (l *ConnectionIDEntryList) Len() int { return l.len }

// Front returns the first element of list l or nil if the list is empty.
func (l *ConnectionIDEntryList) Front() *ConnectionIDEntryElement {
	if l.len == 0 {
		return nil
	}
	return l.root.next
}

// Back returns the last element of list l or nil if the list is empty.
func (l *ConnectionIDEntryList) Back() *ConnectionIDEntryElement {
	if l.len == 0 {
		return nil
	}
	return l.root.prev
}

// lazyInit lazily initializes a zero List value.
func (l *ConnectionIDEntryList) lazyInit() {
	if l.root.next == nil {
		l.Init()
	}
}

// insert inserts e after at, increments l.len, and returns e.
func (l *ConnectionIDEntryList) insert(e, at *ConnectionIDEntryElement) *ConnectionIDEntryElement {
	n := at.next
	at.next = e
	e.prev = at
	e.next = n
	n.prev = e
	e.list = l
	l.len++
	return e
}

// insertValue is a convenience wrapper for insert(&Element{Value: v}, at).
func (l *ConnectionIDEntryList) insertValue(v ConnectionIDEntry, at *ConnectionIDEntryElement) *ConnectionIDEntryElement {
	return l.insert(&ConnectionIDEntryElement{Value: v}, at)
}

// remove removes e from its list, decrements l.len, and returns e.
func (l *ConnectionIDEntryList) remove(e *ConnectionIDEntryElement) *ConnectionIDEntryElement {
	e.prev.next = e.next
	e.next.prev = e.prev
	e.next = nil // avoid memory leaks
	e.prev = nil // avoid memory leaks
	e.list = nil
	l.len--
	return e
}

// Remove removes e from l if e is an element of list l.
// It returns the element value e.Value.
// The element must not be nil.
func (l *ConnectionIDEntryList) Remove(e *ConnectionIDEntryElement) ConnectionIDEntry {
	if e.list == l {
		// if e.list == l, l must have been initialized when e was inserted
		// in l or l == nil (e is a zero Element) and l.remove will crash
		l.remove(e)
	}
	return e.Value
}

// PushFront inserts a new element e with value v at the front of list l and returns e.
func (l *ConnectionIDEntryList) PushFront(v ConnectionIDEntry) *ConnectionIDEntryElement {
	l.lazyInit()
	return l.insertValue(v, &l.root)
}

// PushBack inserts a new element e with value v at the back of list l and returns e.
func (l *ConnectionIDEntryList) PushBack(v ConnectionIDEntry) *ConnectionIDEntryElement {
	l.lazyInit()
	return l.insertValue(v, l.root.prev)
}

// InsertBefore inserts a new element e with value v immediately before mark and returns e.
// If mark is not an element of l, the list is not modified.
// The mark must not be nil.
func (l *ConnectionIDEntryList) InsertBefore(v ConnectionIDEntry, mark *ConnectionIDEntryElement) *ConnectionIDEntryElement {
	if mark.list != l {
		return nil
	}
	// see comment in List.Remove about initialization of l
	return l.insertValue(v, mark.prev)
}

// InsertAfter inserts a new element e with value v immediately after mark and returns e.
// If mark is not an element of l, the list is not modified.
// The mark must not be nil.
func (l *ConnectionIDEntryList) InsertAfter(v ConnectionIDEntry, mark *ConnectionIDEntryElement) *ConnectionIDEntryElement {
	if mark.list != l {
		return nil
	}
	// see comment in List.Remove about initialization of l
	return l.insertValue(v, mark)
}

// MoveToFront moves element e to the front of list l.
// If e is not an element of l, the list is not modified.
// The element must not be nil.
func (l *ConnectionIDEntryList) MoveToFront(e *ConnectionIDEntryElement) {
	if e.list != l || l.root.next == e {
		return
	}
	// see comment in List.Remove about initialization of l
	l.insert(l.remove(e), &l.root)
}

// MoveToBack moves element e to the back of list l.
// If e is not an element of l, the list is not modified.
// The element must not be nil.
func (l *ConnectionIDEntryList) MoveToBack(e *ConnectionIDEntryElement) {
	if e.list != l || l.root.prev == e {
		return
	}
	// see comment in List.Remove about initialization of l
	l.insert(l.remove(e), l.root.prev)
}

// MoveBefore moves element e to its new position before mark.
// If e or mark is not an element of l, or e == mark, the list is not modified.
// The element and mark must not be nil.
func (l *ConnectionIDEntryList) MoveBefore(e, mark *ConnectionIDEntryElement) {
	if e.list != l || e == mark || mark.list != l {
		return
	}
	l.insert(l.remove(e), mark.prev)
}

// MoveAfter moves element e to its new position after mark.
// If e or mark is not an element of l, or e == mark, the list is not modified.
// The element and mark must not be nil.
func (l *ConnectionIDEntryList) MoveAfter(e, mark *ConnectionIDEntryElement) {
	if e.list != l || e == mark || mark.list != l {
		return
	}
	l.insert(l.remove(e), mark)
}

// PushBackList inserts a copy of an other list at the back of list l.
// The lists l and other may be the same. They must not be nil.
func (l *ConnectionIDEntryList) PushBackList(other *ConnectionIDEntryList) {
	l.lazyInit()
	for i, e := other.Len(), other.Front(); i > 0; i, e = i-1, e.Next() {
		l.insertValue(e.Value, l.root.prev)
	}
}

// PushFrontList inserts a copy of an other list at the front of list l.
// The lists l and other may be the same. They must not be nil.
func (l *ConnectionIDEntryList) PushFrontList(other *ConnectionIDEntryList) {
	l.lazyInit()
	for i, e := other.Len(), other.Back(); i > 0; i, e = i-1, e.Prev() {
		l.insertValue(e.Value, &l.root)
	}
}
